### ISSUE TITLE
Fails to concatenate the whole last file.

### ISSUE THREAD

**Issue by saturday** [wearefractal/gulp-concat#64]
I'm using gulp-concat version 2.4.0 and gulp 3.8.7.

This plugin isn't concatenating the whole file in my list of js files. Specifically, it's ignoring a portion of the last JS file in the array.

**Comment by jthuraisamy** [comment]
Here is my task code which does not consistently concatenate all specified files from the modules array:

```javascript
// Process project scripts.
gulp.task('scripts-project', ['transform-jsx', 'jshint'], function() {
    var modules = ['model', 'view', 'controller', 'main'];
    var jsSrcDir = './public/src/scripts/compiled-jsx/';
    var jsDst = './public/build/scripts';
    var jsSrc = modules.map(function(module) { return jsSrcDir + module + '.js'; });

    gulp.src(jsSrc)
        .pipe(sourcemaps.init())
        .pipe(to5())
        .pipe(concat('app.js'))
        .pipe(uglify())
        .pipe(sourcemaps.write('.'))
        .pipe(gulp.dest(jsDst))
});
```

If I understand correctly, this issue seems to occur when concatenating a list of specific files.

**Comment by jthuraisamy** [comment]
A couple more notes:

1. Sometimes changing the order of the files in the `modules` variable helps but there's only a certain extent to which that could be done (otherwise an ordered list would be unnecessary).
2. The issue has occured on both Windows and Linux (Ubuntu).

My repo is [here](https://github.com/jthuraisamy/i88fm-playlist). Since sourcemaps are made in the task, it is apparent in the screenshot below that the `main.js` module specified in the task is missing.

![](http://i.imgur.com/G4UfOc4.png)

**Comment by contra** [comment]
@jthuraisamy Your gulpfile is totally messed up in that repo, you might want to make a new repo that isolates the issues a little better.

**Comment by jthuraisamy** [comment]
You're right, @contra. After more testing with a reduced gulp task, the issue does not seem to be with gulp-concat after all. For example, the following code also intermittently produces an empty `main.js` file.

```javascript
gulp.task('scripts-project', ['transform-jsx', 'jshint'], function() {
    var modules = ['model', 'view', 'controller', 'main'];
    var jsSrcDir = './public/src/scripts/compiled-jsx/';
    var jsDst = './public/build/scripts';
    var jsSrc = modules.map(function(module) { return jsSrcDir + module + '.js'; });

    gulp.src(jsSrc)
        .pipe(gulp.dest(jsDst));
```

Perhaps @beardedinbinary can try his task code a few times without the `.pipe(concat('all.js'))` line, and see if the resulting `feedback.js` and `docCookies.js` are randomly blank.

**Comment by shinnn** [comment]
Does it still occur in v2.5.0?

**Comment by pboutin** [comment]
I can confirm it still occur in the v2.5.2

Here, I would say that `./frontend/tests/integrations/*.js` get ignored about 30% of the time

```JavaScript
gulp.task('concat-test', function() {
    return gulp.src([
        "./frontend/tests/app.js",
        "./frontend/src/router.js",
        "./frontend/src/helpers.js",
        "./frontend/src/inputs.js",
        "./frontend/src/injections/*.js",
        "./frontend/src/mixins/**/*.js",
        "./frontend/src/components/**/*.js",
        "./frontend/src/models/**/*.js",
        "./frontend/src/controllers/**/*.js",
        "./frontend/src/routes/**/*.js",
        "./frontend/src/views/**/*.js",
        "./frontend/src/components.js",
        "./frontend/tests/helpers/*.js",
        "./frontend/tests/fixtures/*.js",
        "./frontend/tests/integrations/*.js"
    ])
    .pipe(concat('test.js'))
    .pipe(gulp.dest('public/js/'));
});
```

**Comment by contra** [comment]
Anybody want to make a repo so I can reproduce?

**Comment by pboutin** [comment]
I will try to put something together for you @contra , I will keep you tuned.

**Comment by pboutin** [comment]
With the same file structure and the isolated gulpfile, I'm not even able to reproduce the bug... that's very strange... I'm lost on that one..

**Comment by shinnn** [comment]
@pboutin Which version of Node are you using?

**Comment by pboutin** [comment]
@shinnn node --version : v0.10.25

**Comment by shinnn** [comment]
@pboutin 

I ran into Buffer-related problem when using older Node, but the problem no longer occurs after I update Node.

I recommend using the latest stable version (v0.12.0) or io.js v1.3.0 whether it fixes gulp-concat problem or not. v0.10.25 is too older version.

**Comment by pboutin** [comment]
Did it with no success... unfortunately

**Comment by pboutin** [comment]
Still bugging, sometimes the last "file selector" is missing, sometimes the first "file selector" is at the end... for no reason...

**Comment by ktrhn** [comment]
Same here. Node 0.12.0, gulp-concat 2.5.2.

**Comment by contra** [comment]
I can't reproduce it and if none of you can either then I don't know how I'm going to debug this one

**Comment by pboutin** [comment]
After updating my Node, the problem persisted. The problem went away after a full reboot (don't know how it could be related but it's what I observed on my side).

Everything runs smoothly now !

**Comment by mrapczynski** [comment]
@contra @pboutin New to Gulp -- I was having this exact problem, but it turned out to be that I was not doing the async plumbing properly from task to task, i.e returning gulp.src.. and specifying task dependencies *per task*. Once I did that, the inconsistency went away.

**Comment by geri777** [comment]
I still have this issue in Gulp 3.9.1 when using gulp-concat. It's not the last file - it's one of the files. I have set dependencies etc. It works for a while after restarting my PC - then the output of that file is empty again.
