### ISSUE TITLE
Concatenated files aren't concatenated safely

### ISSUE THREAD

**Issue by nolanlawson** [wearefractal/gulp-concat#75]
I think to be 100% safe, you need to concatenate files with `;\n`, yes? Currently it looks like this only concatenates with `\n`.

Prompted by https://github.com/nolanlawson/pouchdb-authentication/pull/17.

**Comment by contra** [comment]
@nolanlawson This module is for all types of files, not just JS. If you want to concat with `;\n` then you can do so with the `newLine` option
