### ISSUE TITLE
File reference in sourcemap mismatches file.path

### ISSUE THREAD

**Issue by w0rm** [wearefractal/gulp-concat#77]
Concatenation of three files inside ./src/ creates the following source map:

```
 { version: 3,
  sources: [ 'a.css', 'b.css', 'c.css' ],
  names: [],
  mappings: 'AAAA;AACA;AACA;AACA;ACHA;AACA;AACA;AACA;ACHA;AACA;AACA;AACA',
  file: 'result-postcss.css',
  sourcesContent: 
   [ '.a {\n\ttext-align: center;\n}\n',
     '.b {\n\ttext-align: center;\n}\n',
     '.c {\n\ttext-align: center;\n}\n' ] }
```

The result vinyl file object has path similar to this: `/Users/username/path/to/gulp-postcss-sourcemaps-test/src/result-postcss.css` (note that it includes `src/`).

I think that all file references in sourcemaps should include `src/` because otherwise you cannot combine this sourcemap with further modifications. 

Please find more details here: https://github.com/w0rm/gulp-postcss/issues/18

**Comment by contra** [comment]
cc @floridoo

**Comment by floridoo** [comment]
@w0rm: The paths in the sources array are the same as gulp itself uses. In order to have `src/` included in the path you have two possibilities:
- use a glob not including the dir:
```js
gulp.src('gulp-postcss-sourcemaps-test/**/*.css')
```
- manually set the `base` dir, all source paths are relative to that directory then:
```js
gulp.src('gulp-postcss-sourcemaps-test/src/*.css', { base: 'gulp-postcss-sourcemaps-test' })
```

**Comment by w0rm** [comment]
@floridoo what about result file? Why file.path tells me that file is in src dir, but sourcemap tells it is in cwd?

**Comment by floridoo** [comment]
@w0rm do you mean the `file` property on the source map?
If yes: it contains just the file name of the result file, because `gulp-sourcemaps` doesn't know where you will output the file to (that's just specified in `gulp.dest()`). Afaik the `file` property is optional and not used by browsers.

**Comment by w0rm** [comment]
@floridoo isn't file parameter used to apply one source map on top of another? Because this is what happens when it doesn't match https://github.com/w0rm/gulp-postcss/issues/18#issuecomment-70432460 

If `file.path` is set to include `src` directory, then `file` parameter of source map should also include it. I agree that it is irrelevant to `gulp.dest`, but it is needed to combine source map with subsequent gulp plugins.

**Comment by floridoo** [comment]
@w0rm Yes, it is used when merging source maps.
`file.path` is the absolute path. `file.relative` is the one that is used for the `file` and `sources` properties. It is relative to `base`.

**Comment by w0rm** [comment]
@floridoo Ah, I see. Will reopen original ticket for gulp-postcss.
