### ISSUE TITLE
Concat appends to a file instead of overwriting it.

### ISSUE THREAD

**Issue by TheDutchCoder** [wearefractal/gulp-concat#79]
I can't remember ever having this issue before, but with the latest release concat appends to my file instead of overwriting it.

I use the following task:
```js
gulp.task('js:dist', function() {

    return gulp.src([
            dirs.main + '/' + name + '/js/*.js',
            dirs.main + '/' + name + '/js/plugins/**/*.js'
        ])
        .pipe(plugins.concat('scripts.all.js'))
        .pipe(gulp.dest(dirs.main + '/' + name + '/js/'));

});
```

I would expect it to overwrite `scripts.all.js`, but instead it keeps appending to this file.
Is this a bug or am I overlooking something?

**Comment by TheDutchCoder** [comment]
Nevermind, I totally forgot to ignore the concatenated file in the source :D

**Comment by contra** [comment]
@TheDutchCoder That's why most people have input and output folders to make that simpler

**Comment by TheDutchCoder** [comment]
Yeah fair enough, but I don't find that very practical in a WordPress
environment at the moment.

Got it sorted out though, thanks!

**Comment by madvas** [comment]
hehe same thing happened to me, thanks!
