### ISSUE TITLE
Concat consistently taking longer to complete with v2.4.3

### ISSUE THREAD

**Issue by steverandy** [wearefractal/gulp-concat#80]
Seeing consistent perf drop after upgrading to v2.4.3.

Task with v2.4.2 or lower takes around ~400ms.
Task with v2.4.3 takes around ~900ms or more.

Not sure why. Is it because of the change in dependencies?

**Comment by contra** [comment]
No I don't think so, the update was a minor bug fix - none of the dependencies got slower. 900ms is insane for concat, how many files? Can you post your task?

**Comment by steverandy** [comment]
Around 103 files. Total file size after concat is 3.2MB.

**Comment by contra** [comment]
> Can you post your task?

**Comment by steverandy** [comment]
This is my bundle scripts task https://gist.github.com/steverandy/63694b5ce016fcdc8d16.
There is additional bundles file that lists the source https://gist.github.com/steverandy/468ddd71ea6c72d7f949.

**Comment by contra** [comment]
@steverandy How do you know that concat is the slow piece? Can you isolate this into a test that only includes the concat plugin, and then test between the two versions where you think there was a regression?

**Comment by steverandy** [comment]
I have created the test here: https://github.com/steverandy/gulp-concat-bench
All it does is concatenating 60 underscore.js files.
You just need to run `npm start`.
I don't know how to require both versions with npm. The easiest way is to just replace the version in package.json.

Results on my machine:
v2.4.3: gulp-concat x 4.09 ops/sec ±10.15% (25 runs sampled)
v2.4.2: gulp-concat x 10.97 ops/sec ±6.68% (57 runs sampled)

**Comment by contra** [comment]
100ms to concat 60 files is excessive, will take a look when I have a minute

**Comment by contra** [comment]
cc @floridoo who wrote the module that powers this one. The issue is probably there, will set up some benchmarks

**Comment by shinnn** [comment]
Maybe [this change](https://github.com/floridoo/concat-with-sourcemaps/commit/80702596b24bba7b86a89a3d7e02b933969de970#diff-168726dbe96b3ce427e7fedce31bb0bcR46) for binary support increased concatenation time.
I created a PR for performance improvement. https://github.com/floridoo/concat-with-sourcemaps/pull/7

Benchmark results on my machine:
v2.4.3: gulp-concat x 6.41 ops/sec ±1.84% (35 runs sampled)
v2.4.2: gulp-concat x 14.08 ops/sec ±3.01% (70 runs sampled)
v2.5.0: gulp-concat x 6.65 ops/sec ±2.36% (36 runs sampled)
v2.5.0 with my update: gulp-concat x 7.40 ops/sec ±2.39% (40 runs sampled)

**Comment by contra** [comment]
@shinnn Commented on the PR pretty sure I identified the problem

**Comment by floridoo** [comment]
Version 1.0.2 of `concat-with-sourcemaps` should fix the speed regression (tested with @steverandy's benchmark)

**Comment by contra** [comment]
@floridoo :palm_tree:

**Comment by steverandy** [comment]
Thanks for the fix!
