### ISSUE TITLE
Buffer is `required` but not used anywhere

### ISSUE THREAD

**Issue by evansd** [wearefractal/gulp-concat#81]
`index.js` contains this line:
```js
var Buffer = require('buffer').Buffer;
```
But the variable `Buffer` is no longer referenced anywhere in the file.

**Comment by contra** [comment]
PR? Must be a relic from old code

**Comment by evansd** [comment]
Just happened to notice this while reading the code. PR submitted now.

**Comment by contra** [comment]
Thanks!
