### ISSUE TITLE
Files not being concatenated in deterministic order

### ISSUE THREAD

**Issue by prettycode** [wearefractal/gulp-concat#83]
I'm running the following gulp task:

    var outputFiles = {
        compiledStyles: '/styles/app-compiled.css'
    };

    var sourcePaths = {
        styles: ['/styles/*.css']
    };

    gulp.task('compile-styles', function() {
        var concatOutputPath = path.dirname(outputFiles.compiledStyles), 
            concatOutputFileName = path.basename(outputFiles.compiledStyles),
            styleFiles = [].concat(
                sourcePaths.styles,
                notpath(outputFiles.compiledStyles)
            );

        del(outputFiles.compiledStyles);

        return gulp
            .src(styleFiles)
            .pipe(buildTools.concat(concatOutputFileName))
            .pipe(gulp.dest(concatOutputPath));
    });

Sometimes when I run `compile-styles`, the order of a couple files toward the end of `outputFileName` is different. In other words, inside `outputFileName`, I always see the [content] of each file this:

    [file1.css]
    [file2.css]
    [file3.css]
    [file4.css]
    [file5.css]

...except sometimes, maybe every other time or every third time I run `compile-styles` I'll see this:

    [file1.css]
    [file2.css]
    [file3.css]
    [file5.css]
    [file4.css]

...where the order of `file5.css` and `file4.css` has swapped.

The function `notpath()` simply takes a string or array of strings and prepends `!` before them, then returns that array. (If `notpath` receives a string argument, it returns it wrapped in an array.)

Not sure if this is an issue with `concat` or `gulp.src` or npm's globbing maybe?

**Comment by contra** [comment]
Can you log out the styleFiles variable being passed to gulp.src when it is working and not working? I doubt it has anything to do with this plugin, I think it is how you are creating that variable.

**Comment by prettycode** [comment]
Sorry to bother--I found some other threads that indicates this issue is not `concat`, e.g. https://github.com/gulpjs/gulp/issues/687
