### ISSUE TITLE
multiple gulp concat - not supported ?

### ISSUE THREAD

**Issue by raDiesle** [wearefractal/gulp-concat#92]
Hi,

using 

gulp.src("file.js")
.pipe(concat("file2.js"))
.pipe(concat("file3.js"))
.pipe(gulp.dest("file4.js"));

will not put all files into dest.
Is this expected ?
If true, why does it makes a difference when operating on streams ?

I know using  gulp.src(["file.js", "file2.js", "file3.js", "file4.js"]) will fix it.

**Comment by contra** [comment]
What are you expecting to happen here?

**Comment by naeramarth7** [comment]
Behaviour of `gulp-concat` is correct. What your code actually does is renaming `file.js` to `file4.js`:

    gulp.src("file.js")             // 1
    .pipe(concat("file2.js"))       // 2
    .pipe(concat("file3.js"))       // 3
    .pipe(gulp.dest("file4.js"));   // 4

1. Put `file.js` **only** into the stream
2. Concat all vinyl files into a single file called `file2.js` - the only file in the stream is `file.js` so your actually just renaming it to `file2.js`
3. Concat all vinyl files into a single file called `file3.js` - same as in step 2
4. Write the vinyl files from stream to a file called `file4.js`

> I know using gulp.src(["file.js", "file2.js", "file3.js", "file4.js"]) will fix it.

This will not just *fix it*, it is the correct way to use streams and `gulp-concat`.
