### ISSUE TITLE
gulp-concat with gulp-changed

### ISSUE THREAD

**Issue by erikkemperman** [wearefractal/gulp-concat#96]
Hi,

When the destination file is passed in as a string, gulp-concat clones the attributes of its first source file. That includes stats.mtime, so piping the joined file through gulp-changed will give different results for the case where the first source had changed since the previous build and the case where any of the other sources had changed...

Would it make sense to clone the attributes of the most recently changed source file, instead of the first? Or is it some kind of convention (I'm a bit new to gulp) to use the first file in such situations?

Thanks!

**Comment by erikkemperman** [comment]
Figured I'd illustrate this with an example.

_gulpfile.js_
```js
var gulp = require( 'gulp' );
var changed = require( 'gulp-changed' );
var concat = require( 'gulp-concat' );


gulp.task( 'default', function() {
  return gulp.src( 'part-*.js' )
    .pipe( concat( 'list.js' ) )
    .pipe( changed( '.' ) )
    .pipe( gulp.dest( '.' ) )
  ;
} );
```

_part-1.js_
```js
console.log( 'part-1' );
```

_part-2.js_
```js
console.log( 'part-2' );
```

Running gulp produces the correct _list.js_:
```js
console.log( 'part-1' );

console.log( 'part-2' );
```

Re-running gulp without any changes leaves _list.js_ untouched, as expected.

Editing _part-1.js_ and re-running gulp updates _list.js_, as expected:
```js
console.log( 'part-1 changed' );

console.log( 'part-2' );
```

But editing _part-2.js_ and re-running gulp does not pass through gulp-changed and so it leaves _list.js_ untouched!

**Comment by contra** [comment]
Yeah that makes a lot of sense, want to send a PR?

**Comment by erikkemperman** [comment]
Thanks for the quick reply!

Well, since my earlier post, I've decided I will try my hand at first very own gulp plugin, `gulp-touch` or something like that, to simply set state.mtime of all sources to the maximum amongst them.

That would be a slightly  more elegant solution, because then I can swap `gulp-concat` and `gulp-changed` around in my task, meaning that the concatenation can be avoided as well, when the inputs were not changed. No offence, natch.

```js
var touch = require( 'gulp-touch' );  // <--
gulp.task( 'default', function() {
  return gulp.src( 'part-*.js' )
    .pipe( touch() )                  // <--
    .pipe( changed( '.' ) )           // <--
    .pipe( concat( 'list.js' ) )
    .pipe( gulp.dest( '.' ) )
  ;
} );
```
Also, this might prove useful with other "merging plugins" that produce one output from several inputs.

But anyway, to the extent that cloning the first encountered file's attributes in `gulp-concat` is kind of an arbitrary choice, I still think my original suggestion is valid. I've spent a little time with the code earlier today, but it looks like it's slightly more complicated than just `s/firstFile/latestFile/` and adding  the mtime test...

For one thing, I wouldn't know what to do when the `dest` argument is an object, maybe even an actual `File` with its own stats to consider (I noticed the tests pass `{path:'...'}` for that case?)

Anyway, as you can probably tell I'm new around here -- so I'd like to spend just a little more time playing around before I'm comfortable sending PRs... And I'd first like to do this `gulp-touch` experiment!

**Comment by contra** [comment]
@erikkemperman I think that should be built into the plugin though, not something the user has to specify. It's good to have it as a module that other plugins can rely on though

**Comment by erikkemperman** [comment]
Thanks for merging my PR! One more thing: is this something you'd consider releasing as a new version?

**Comment by contra** [comment]
@erikkemperman 2.6.0
